name: base_getx
description: temp_package_description

version: 1.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  flutter_screenutil: ^5.8.4
  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  connectivity_plus: ^4.0.1
  hive: ^2.0.4
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  image_picker: ^1.0.0
  image_cropper: ^5.0.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^5.1.0
  intl: ^0.18.1
  gap: ^3.0.1
  flutter_switch: ^0.3.2
  build_runner: ^2.1.2
  hive_generator: ^2.0.0
  flutter_portal: ^1.1.4
  flutter_spinkit: ^5.2.0
  overlay_support: ^2.1.0
  flutter_easyrefresh: ^2.2.1



  #config firebase
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^9.9.1-dev.2
  firebase_auth: ^4.9.0


  # Login social
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.1
  zalo_flutter: ^0.0.5
  sign_in_with_apple: ^5.0.0

dependency_overrides:
  http: ^1.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/png/logo_1024.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 
