name: temp_package_name
description: temp_package_description

version: 1.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  get_it: ^7.6.0
  easy_localization: ^3.0.2
  go_router: ^9.0.0
  flutter_screenutil: ^5.8.4
  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  connectivity_plus: ^4.0.1
  hive: ^2.0.4
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  image_picker: ^1.0.0
  image_cropper: ^5.0.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^5.1.0
  intl: ^0.18.1
  gap: ^3.0.1
  flutter_switch: ^0.3.2
  build_runner: ^2.1.2
  hive_generator: ^2.0.0
  flutter_portal: ^1.1.4
  #config firebase
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1


dependency_overrides:
  http: ^1.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/png/logo_1024.png"

jsonToDart:
  typeChecking: true  #default: undefined (Select from picker)
  nullValueDataType: dynamic #default: dynamic
  nullSafety: true #default: false
  copyWithMethod: false #default: false
  mergeArrayApproach: false #default: true 

flutter:
  uses-material-design: true
  assets:
    - assets/translation/
    - assets/images/ 
    - assets/images/svg/ 
    - assets/images/png/ 
